3100 #!/usr/bin/perl -w
3101 
3102 # Generate vectors.S, the trap/interrupt entry points.
3103 # There has to be one entry point per interrupt number
3104 # since otherwise there's no way for trap() to discover
3105 # the interrupt number.
3106 
3107 print "# generated by vectors.pl - do not edit\n";
3108 print "# handlers\n";
3109 print ".text\n";
3110 print ".globl alltraps\n";
3111 for(my $i = 0; $i < 256; $i++){
3112     print ".globl vector$i\n";
3113     print "vector$i:\n";
3114     if(($i < 8 || $i > 14) && $i != 17){
3115         print "  pushl \$0\n";
3116     }
3117     print "  pushl \$$i\n";
3118     print "  jmp alltraps\n";
3119 }
3120 
3121 print "\n# vector table\n";
3122 print ".data\n";
3123 print ".globl vectors\n";
3124 print "vectors:\n";
3125 for(my $i = 0; $i < 256; $i++){
3126     print "  .long vector$i\n";
3127 }
3128 
3129 # sample output:
3130 #   # handlers
3131 #   .text
3132 #   .globl alltraps
3133 #   .globl vector0
3134 #   vector0:
3135 #     pushl $0
3136 #     pushl $0
3137 #     jmp alltraps
3138 #   ...
3139 #
3140 #   # vector table
3141 #   .data
3142 #   .globl vectors
3143 #   vectors:
3144 #     .long vector0
3145 #     .long vector1
3146 #     .long vector2
3147 #   ...
3148 
3149 
